
    -- Intentamos crear el usuario usando la tablespace USERS
    BEGIN
       EXECUTE IMMEDIATE 'CREATE USER stage IDENTIFIED BY stage123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
    EXCEPTION
       WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Fallo con USERS. Intentando con SYSTEM...');
          EXECUTE IMMEDIATE 'CREATE USER stage IDENTIFIED BY stage123 DEFAULT TABLESPACE system QUOTA UNLIMITED ON system';
    END;
    /
    
    BEGIN
       EXECUTE IMMEDIATE 'CREATE USER dw IDENTIFIED BY dw123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
    EXCEPTION
       WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Fallo con USERS. Intentando con SYSTEM...');
          EXECUTE IMMEDIATE 'CREATE USER dw IDENTIFIED BY dw123 DEFAULT TABLESPACE system QUOTA UNLIMITED ON system';
    END;
    /
    
    BEGIN
       EXECUTE IMMEDIATE 'CREATE USER produccion IDENTIFIED BY prod123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
    EXCEPTION
       WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Fallo con USERS. Intentando con SYSTEM...');
          EXECUTE IMMEDIATE 'CREATE USER produccion IDENTIFIED BY prod123 DEFAULT TABLESPACE system QUOTA UNLIMITED ON system';
    END;
    /


GRANT CONNECT, RESOURCE TO stage;
GRANT CREATE SESSION TO stage;
GRANT CREATE TABLE TO stage;
GRANT UNLIMITED TABLESPACE TO stage;

GRANT CONNECT, RESOURCE TO dw;
GRANT CREATE SESSION TO dw;
GRANT CREATE TABLE TO dw;
GRANT UNLIMITED TABLESPACE TO dw;


GRANT CONNECT, RESOURCE TO produccion;
GRANT CREATE SESSION TO produccion;
GRANT CREATE TABLE TO produccion;
GRANT UNLIMITED TABLESPACE TO produccion;

SELECT username FROM dba_users WHERE username IN ('STAGE', 'DW', 'PRODUCCION');






