
CREATE TABLE BD2_DIM_HORA
   ( HORA_KEY 	NUMBER,
     HORA		VARCHAR2(5 BYTE)
   ) ;
   
ALTER TABLE BD2_DIM_HORA ADD CONSTRAINT HORA_PK
  PRIMARY KEY ( HORA_KEY );
   
--------------------------------------------------------

CREATE TABLE BD2_DIM_SELECCION
   ( SELECCION_KEY 		NUMBER,
     NOMBRE_SELECCION	VARCHAR2(100 BYTE)
   ) ;

ALTER TABLE BD2_DIM_SELECCION ADD CONSTRAINT SELECCION_PK
  PRIMARY KEY ( SELECCION_KEY );
  
--------------------------------------------------------

CREATE TABLE BD2_DIM_RONDA
   ( RONDA_KEY 		NUMBER,
     NOMBRE_RONDA	VARCHAR2(50 BYTE)
   ) ;
   
ALTER TABLE BD2_DIM_RONDA ADD CONSTRAINT RONDA_PK
  PRIMARY KEY ( RONDA_KEY );
  
--------------------------------------------------------

CREATE TABLE BD2_DIM_PAIS_ORGANIZADOR
   ( PAIS_KEY 				NUMBER,
     NOMBRE_PAIS_ORGANIZADOR	VARCHAR2(100 BYTE)
   ) ;

ALTER TABLE BD2_DIM_PAIS_ORGANIZADOR ADD CONSTRAINT PAIS_ORGANIZADOR_PK
  PRIMARY KEY ( PAIS_KEY );

-----------------------Parte del 18 al 25--------------------------
   
CREATE TABLE BD2_DIM_CIUDAD
   ( CIUDAD_KEY 				NUMBER,
     CIUDAD_ORGANIZADOR			VARCHAR2(100 BYTE),
	 PAIS_KEY 					NUMBER
   ) ;

ALTER TABLE BD2_DIM_CIUDAD ADD CONSTRAINT CIUDAD_PK
  PRIMARY KEY ( CIUDAD_KEY );

ALTER TABLE BD2_DIM_CIUDAD ADD CONSTRAINT FK_CIUDAD_PAIS
  FOREIGN KEY ( PAIS_KEY )
 REFERENCES BD2_DIM_PAIS_ORGANIZADOR ( PAIS_KEY ) ;
 
--------------------------------------------------------

CREATE TABLE BD2_DIM_ESTADIO
   ( ESTADIO_KEY 		NUMBER,
     NOMBRE_ESTADIO		VARCHAR2(100 BYTE),
	 CIUDAD_KEY			NUMBER
   ) ;

ALTER TABLE BD2_DIM_ESTADIO ADD CONSTRAINT ESTADIO_PK
  PRIMARY KEY ( ESTADIO_KEY );

ALTER TABLE BD2_DIM_ESTADIO ADD CONSTRAINT FK_ESTADIO_CIUDAD
  FOREIGN KEY ( CIUDAD_KEY )
 REFERENCES BD2_DIM_CIUDAD ( CIUDAD_KEY ) ;

--------------------------------------------------------

CREATE TABLE BD2_HECHOS
   ( ANIO 			NUMBER,
     FECHA_KEY  	NUMBER,
	 HORA_KEY		NUMBER,
	 RONDA_KEY		NUMBER,
	 ESTADIO_KEY	NUMBER,
	 LOCAL_KEY		NUMBER,
	 VISITANTE_KEY	NUMBER,
	 GOL_LOCAL		NUMBER,
	 GOL_VISITA		NUMBER,
	 ASISTENCIA		NUMBER
   ) ;

--------------------------------------------------------

CREATE TABLE BD2_NO_HECHOS
   ( ANIO 			NUMBER,
     FECHA_KEY  	NUMBER,
	 FECHA_COD  	DATE,
	 HORA_KEY		NUMBER,
	 HORA_COD  		VARCHAR2(5 BYTE),
	 RONDA_KEY		NUMBER,
	 NOMBRE_RONDA	VARCHAR2(50 BYTE),
	 ESTADIO_KEY	NUMBER,
	 ESTADIO		VARCHAR2(100 BYTE),
	 CIUDAD			VARCHAR2(100 BYTE),
	 PAIS			VARCHAR2(100 BYTE),
	 LOCAL_KEY		NUMBER,
	 EQUIPO_LOCAL	VARCHAR2(100 BYTE),
	 VISITANTE_KEY	NUMBER,
	 EQUIPO_VISITA	VARCHAR2(100 BYTE),
	 GOL_LOCAL		NUMBER,
	 GOL_VISITA		NUMBER,
	 ASISTENCIA		NUMBER
   ) ;

--------------------------------------------------------

CREATE TABLE BD2_CORRELATIVOS
   ( DIMENSION VARCHAR2(30 BYTE), 
	 VALOR NUMBER(5,0)
   ) ;
   
--------------------------------------------------------

  CREATE TABLE BD2_SEGUIMIENTO
   ( DIMENSION VARCHAR2(30 BYTE), 
	 USUARIO VARCHAR2(30 BYTE), 
	 FECHA DATE
   ) ;
   
--------------------------------------------------------

  CREATE TABLE BD2_VALORES_DEFAULT
   ( CAMPO VARCHAR2(30 BYTE), 
	 VALOR NUMBER(38,2)
   ) ;
   
--------------------------------------------------------

GRANT SELECT ON BD2_HECHOS TO stage;
GRANT SELECT ON BD2_DIM_HORA TO stage;
GRANT SELECT ON BD2_DIM_RONDA TO stage;
GRANT SELECT ON BD2_DIM_ESTADIO TO stage;
GRANT SELECT ON BD2_DIM_CIUDAD TO stage;
GRANT SELECT ON BD2_DIM_PAIS_ORGANIZADOR TO stage;
GRANT SELECT ON BD2_DIM_SELECCION TO stage;