-- ============================================
-- TRIGGERS EN PRODUCCIÓN PARA WATERMARK
-- ============================================
CREATE OR REPLACE TRIGGER BD2_STG_DATOS
AFTER INSERT OR UPDATE OR SELECT ON BD2_HECHOS
FOR EACH ROW
BEGIN
  INSERT INTO WATERMARK (TABLA, PK, OPERACION, FECHA_INSERT)
  VALUES ('BD2_STG_DATOS', :NEW.ANIO, 
          CASE 
            WHEN INSERTING THEN 'I'
            WHEN UPDATING THEN 'U'
            WHEN SELECTING THEN 'S'
          END,
          SYSDATE);
END;
/


CREATE OR REPLACE PROCEDURE PRC_SINCRONIZACION IS
BEGIN
  FOR r IN (SELECT * FROM WATERMARK WHERE MIGRO = 'N') LOOP
    DELETE FROM BD2_STG_DATOS WHERE ANIO = r.PK;

    INSERT INTO BD2_STG_DATOS
    SELECT * FROM BD2_HECHOS@PRODUCCION_LINK WHERE ANIO = r.PK;

    UPDATE WATERMARK SET MIGRO = 'S', FECHA_OPERADO = SYSDATE
    WHERE PK = r.PK AND TABLA = 'BD2_HECHOS';
  END LOOP;
END;
/
