

-- ============================================
-- PROCEDIMIENTO DE LLENADO DE HECHOS
-- ============================================
CREATE OR REPLACE PROCEDURE PRC_CONSTRUYE_HECHOS(p_param IN NUMBER) IS
BEGIN
  IF p_param = 1 THEN
    FOR r IN (
      SELECT * FROM BD2_STG_DATOS S
      LEFT JOIN BD2_DIM_HORA H ON S.HORA = H.HORA
      LEFT JOIN BD2_DIM_RONDA RON ON S.RONDA = RON.NOMBRE_RONDA
      LEFT JOIN BD2_DIM_ESTADIO EST ON S.ESTADIO = EST.NOMBRE_ESTADIO
      LEFT JOIN BD2_DIM_CIUDAD C ON S.CIUDAD = C.CIUDAD_ORGANIZADOR
      LEFT JOIN BD2_DIM_PAIS_ORGANIZADOR P ON S.PAIS = P.NOMBRE_PAIS_ORGANIZADOR
      LEFT JOIN BD2_DIM_SELECCION L ON S.EQUIPO_LOCAL = L.NOMBRE_SELECCION
      LEFT JOIN BD2_DIM_SELECCION V ON S.EQUIPO_VISITA = V.NOMBRE_SELECCION
    ) LOOP
      IF r.HORA_KEY IS NOT NULL AND r.RONDA_KEY IS NOT NULL AND r.ESTADIO_KEY IS NOT NULL AND
         r.CIUDAD_KEY IS NOT NULL AND r.PAIS_KEY IS NOT NULL AND r.LOCAL_KEY IS NOT NULL AND r.VISITANTE_KEY IS NOT NULL THEN
        INSERT INTO BD2_HECHOS VALUES (
          r.ANIO, TO_NUMBER(TO_CHAR(r.FECHA, 'YYYYMMDD')), r.HORA_KEY, r.RONDA_KEY,
          r.ESTADIO_KEY, r.LOCAL_KEY, r.VISITANTE_KEY, r.GOL_LOCAL, r.GOL_VISITA, r.ASISTENCIA
        );
      ELSE
        INSERT INTO BD2_NO_HECHOS (...); -- rellenar campos
      END IF;
    END LOOP;
  ELSIF p_param = 2 THEN
    FOR r IN (
      SELECT * FROM BD2_NO_HECHOS NH
      LEFT JOIN BD2_DIM_HORA H ON NH.HORA_COD = H.HORA
      -- Agregar los demás LEFT JOIN
    ) LOOP
      INSERT INTO BD2_HECHOS (...); -- rellenar campos
    END LOOP;
  END IF;
END;
/



-- ============================================
-- PROCEDIMIENTO PARA DETECTAR DIMENSIONES CON KEYS NULAS
-- ============================================
CREATE OR REPLACE PROCEDURE PRC_DIMENSIONES_FALTANTES IS
BEGIN
  FOR r IN (
    SELECT DISTINCT 'BD2_DIM_HORA' AS DIM FROM BD2_NO_HECHOS WHERE HORA_KEY IS NULL
    UNION ALL
    SELECT DISTINCT 'BD2_DIM_RONDA' FROM BD2_NO_HECHOS WHERE RONDA_KEY IS NULL
    UNION ALL
    SELECT DISTINCT 'BD2_DIM_ESTADIO' FROM BD2_NO_HECHOS WHERE ESTADIO_KEY IS NULL
    UNION ALL
    SELECT DISTINCT 'BD2_DIM_CIUDAD' FROM BD2_NO_HECHOS WHERE CIUDAD IS NULL
    UNION ALL
    SELECT DISTINCT 'BD2_DIM_PAIS_ORGANIZADOR' FROM BD2_NO_HECHOS WHERE PAIS IS NULL
    UNION ALL
    SELECT DISTINCT 'BD2_DIM_SELECCION' FROM BD2_NO_HECHOS WHERE EQUIPO_LOCAL IS NULL OR EQUIPO_VISITA IS NULL
  ) LOOP
    IF r.DIM = 'BD2_DIM_HORA' THEN PRC_DIM_HORA(2);
    ELSIF r.DIM = 'BD2_DIM_RONDA' THEN PRC_DIM_RONDA(2);
    -- Y así sucesivamente para las demás dimensiones
    END IF;
  END LOOP;
END;
/
