CREATE OR REPLACE PROCEDURE DW.PRC_CONSTRUYE_HECHOS(P_PARAM IN NUMBER) AS
BEGIN
    IF P_PARAM = 2 THEN
        INSERT INTO DW.BD2_HECHOS (
            FECHA_KEY, HORA_KEY, RONDA_KEY, ESTADIO_KEY, CIUDAD_KEY,
            VS_KEY, ARBITRO_KEY, PUBLICO_KEY, VENTA_KEY, EQUIPO_KEY,
            GOLES, TIROS, FALTAS, FUERAS_JUEGO, CORNERS, PENALTIS
        )
        SELECT 
            NH.FECHA_KEY, NH.HORA_KEY, NH.RONDA_KEY, NH.ESTADIO_KEY, NH.CIUDAD_KEY,
            NH.VS_KEY, NH.ARBITRO_KEY, NH.PUBLICO_KEY, NH.VENTA_KEY, NH.EQUIPO_KEY,
            NH.GOLES, NH.TIROS, NH.FALTAS, NH.FUERAS_JUEGO, NH.CORNERS, NH.PENALTIS
        FROM DW.BD2_NO_HECHOS NH
        LEFT JOIN DW.BD2_DIM_TIEMPO T ON NH.FECHA_KEY = T.FECHA_KEY
        WHERE NH.FECHA_KEY IS NOT NULL;

        -- Llenar tabla de seguimiento
        DW.PRC_LLENA_SEGUIMIENTO('PRC_CONSTRUYE_HECHOS 2');

        -- Llenar tabla de WATERMARK en producción
        INSERT INTO PRODUCCION.WATERMARK (TABLA, OPERACION, FECHA, USUARIO)
        VALUES ('BD2_HECHOS', 'INSERT', SYSDATE, USER);
    END IF;
END;
/