-- Limpia los campos de la tabla BD2_STG_DATOS antes de insertar nuevos datos
CREATE OR REPLACE TRIGGER TRG_LIMPIEZA_STG
BEFORE INSERT ON STAGE.BD2_STG_DATOS
FOR EACH ROW
BEGIN
  :NEW.HORA := TRIM(:NEW.HORA);
  :NEW.RONDA := TRIM(:NEW.RONDA);
  :NEW.ESTADIO := TRIM(:NEW.ESTADIO);
  :NEW.CIUDAD := TRIM(:NEW.CIUDAD);
  :NEW.PAIS := TRIM(:NEW.PAIS);
  :NEW.EQUIPO_LOCAL := TRIM(:NEW.EQUIPO_LOCAL);
  :NEW.EQUIPO_VISITA := TRIM(:NEW.EQUIPO_VISITA);
END;
/

CREATE OR REPLACE PROCEDURE DW.PRC_EJECUTA_FLUJO_COMPLETO IS
BEGIN
  DW.PRC_DIM_HORA(1);
  DW.PRC_DIM_RONDA(1);
  DW.PRC_DIM_ESTADIO(1);
  DW.PRC_DIM_CIUDAD(1);
  DW.PRC_DIM_PAIS_ORGANIZADOR(1);
  DW.PRC_DIM_SELECCION(1);

  DW.PRC_CONSTRUYE_HECHOS(1);

  DW.PRC_DIMENSIONES_FALTANTES;

  DW.PRC_CONSTRUYE_HECHOS(2);
END;
/

CALL DW.PRC_EJECUTA_FLUJO_COMPLETO();
