
CREATE OR REPLACE PROCEDURE DW.PRC_EJECUTA_FLUJO_COMPLETO IS
BEGIN
  DW.PRC_DIM_HORA(1);
  DW.PRC_DIM_RONDA(1);
  DW.PRC_DIM_ESTADIO(1);
  DW.PRC_DIM_CIUDAD(1);
  DW.PRC_DIM_PAIS_ORGANIZADOR(1);
  DW.PRC_DIM_SELECCION(1);

  DW.PRC_CONSTRUYE_HECHOS(1);

  DW.PRC_DIMENSIONES_FALTANTES();

  DW.PRC_CONSTRUYE_HECHOS(2);
END;
/

CALL DW.PRC_EJECUTA_FLUJO_COMPLETO();
