CREATE OR REPLACE VIEW DW.VW_REPORTE_HECHOS AS
SELECT
    H.ANIO,
    H.GOL_LOCAL,
    H.GOL_VISITA,
    H.ASISTENCIA,

    HORA.HORA,
    RONDA.NOMBRE_RONDA,
    ESTADIO.NOMBRE_ESTADIO,
    CIUDAD.CIUDAD_ORGANIZADOR,
    PAIS.NOMBRE_PAIS_ORGANIZADOR,

    SL.NOMBRE_SELECCION AS EQUIPO_LOCAL,
    SV.NOMBRE_SELECCION AS EQUIPO_VISITA

FROM DW.BD2_HECHOS H
    LEFT JOIN DW.BD2_DIM_HORA HORA ON H.HORA_KEY = HORA.HORA_KEY
    LEFT JOIN DW.BD2_DIM_RONDA RONDA ON H.RONDA_KEY = RONDA.RONDA_KEY
    LEFT JOIN DW.BD2_DIM_ESTADIO ESTADIO ON H.ESTADIO_KEY = ESTADIO.ESTADIO_KEY
    LEFT JOIN DW.BD2_DIM_CIUDAD CIUDAD ON ESTADIO.CIUDAD_KEY = CIUDAD.CIUDAD_KEY
    LEFT JOIN DW.BD2_DIM_PAIS_ORGANIZADOR PAIS ON CIUDAD.PAIS_KEY = PAIS.PAIS_KEY
    LEFT JOIN DW.BD2_DIM_SELECCION SL ON H.LOCAL_KEY = SL.SELECCION_KEY
    LEFT JOIN DW.BD2_DIM_SELECCION SV ON H.VISITANTE_KEY = SV.SELECCION_KEY