CREATE VIEW PROYECTO_BASES_2022 AS
SELECT HORA_O.DSC_HORA_OCURRENCIA,
G_HORA.DSC_G_HORA_OCURRENCIA,
G_HORA_5.DSC_G_HORA_5,
DEPTO.DSC_DEPARTAMENTO,
MUNI.DSC_MUNICIPIO,
ZONA.DSC_ZONA,
GEN.DSC_GENERO,
/*EDAD.DSC_EDAD,*/
EDAD_80.DSC_G_EDAD_80_MAS,
EDAD_60.DSC_G_EDAD_60_MAS,
EDAD_Q.DSC_EDAD_QUINCENAL,
MAYMEN.DSC_MAYOR_MENOR,
TIPV.DSC_TIPO_VEHICULO,
MARCA.DSC_MARCA_VEHICULO,
COLOR.DSC_COLOR_VEHICULO,
MODELO.DSC_MODELO_VEHICULO,
G_MOD.DSC_G_MODELO_VEHICULO,
TIPEVEN.DSC_TIPO_EVENTO,
FALL.DSC_FALLECIDO_LESIONADO,
INTER.DSC_INTERNADO,
TIE.ANIO,
TIE.MES,
TIE.NOMBRE_MES,
TIE.DIA,
TIE.DIA_SEMANA,
TIE.NOMBRE_DIA,
TIE.SEMANA,
TIE.NOMBRE_SEMESTRE,
TIE.NOMBRE_CUATRIMESTRE,
TIE.NOMBRE_TRIMESTRE,
TIE.FECHA_SEMANA,
H.CANTIDAD_PERSONAS,
H.GTOS_CALC_PER AS GASTOS_PERSONAS,
H.GTOS_CALC_BIE AS GASTOS_BIENES
FROM HECHOS H
INNER JOIN DIM_CAT_HORA_OCURRENCIA HORA_O ON (H.HORA_OCURRENCIA_KEY =
HORA_O.HORA_KEY)
INNER JOIN DIM_CAT_G_HORA G_HORA ON (H.G_HORA_KEY = G_HORA.G_HORA_KEY)
INNER JOIN DIM_CAT_G_HORA_5 G_HORA_5 ON (H.G_HORA_5_KEY =
G_HORA_5.G_HORA_5_KEY)
INNER JOIN DIM_CAT_DEPARTAMENTO DEPTO ON (H.DEPARTAMENTO_KEY =
DEPTO.DEPARTAMENTO_KEY)
INNER JOIN DIM_CAT_MUNICIPIO MUNI ON (H.MUNICIPIO_KEY = MUNI.MUNICIPIO_KEY)
INNER JOIN DIM_CAT_ZONA ZONA ON (H.ZONA_OCURRENCIA_KEY = ZONA.ZONA_KEY)
INNER JOIN DIM_CAT_GENERO GEN ON (H.GENERO_KEY = GEN.GENERO_KEY)
/*INNER JOIN DIM_CAT_EDAD EDAD ON (H.EDAD_PERSONA_KEY = EDAD.EDAD_KEY) */
INNER JOIN DIM_CAT_G_EDAD_80_MAS EDAD_80 ON (H.G_EDAD_80_MAS_KEY =
EDAD_80.G_EDAD_80_MAS_KEY)
INNER JOIN DIM_CAT_G_EDAD_60_MAS EDAD_60 ON (H.G_EDAD_60_MAS_KEY =
EDAD_60.G_EDAD_60_MAS_KEY)
INNER JOIN DIM_CAT_EDAD_QUINCENAL EDAD_Q ON (H.EDAD_QUINCENAL_KEY =
EDAD_Q.EDAD_QUINCENAL_KEY)
INNER JOIN DIM_CAT_MAYOR_MENOR MAYMEN ON (H.MAYOR_MENOR_KEY =
MAYMEN.MAYOR_MENOR_KEY)
INNER JOIN DIM_CAT_TIPO_VEHICULO TIPV ON (H.TIPO_VEHICULO_KEY =
TIPV.TIPO_VEHICULO_KEY)
INNER JOIN DIM_CAT_MARCA_VEHICULO MARCA ON (H.MARCA_VEHICULO_KEY =
MARCA.MARCA_VEHICULO_KEY)
INNER JOIN DIM_CAT_COLOR_VEHICULO COLOR ON (H.COLOR_VEHICULO_KEY =
COLOR.COLOR_VEHICULO_KEY)
INNER JOIN DIM_CAT_MODELO_VEHICULO MODELO ON (H.MODELO_VEHICULO_KEY =
MODELO.MODELO_VEHICULO_KEY)
INNER JOIN DIM_CAT_G_MODELO_VEHICULO G_MOD ON (H.G_MODELO_VEHICULO_KEY =
G_MOD.G_MODELO_VEHICULO_KEY)
INNER JOIN DIM_CAT_TIPO_EVENTO TIPEVEN ON (H.TIPO_EVENTO_KEY =
TIPEVEN.TIPO_EVENTO_KEY)
INNER JOIN DIM_CAT_FALLECIDO_LESIONADO FALL ON (H.FALLECIDO_LESIONADO_KEY =
FALL.FALLECIDO_LESIONADO_KEY)
INNER JOIN DIM_CAT_INTERNADO INTER ON (H.INTERNADO_KEY = INTER.INTERNADO_KEY)
INNER JOIN DIM_TIEMPO TIE ON (H.FECHA_KEY = TIE.FECHA_KEY)
;
