version: "3.8"
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    environment:
      - ORACLE_PWD=system123
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./csv/:/home/

volumes:
  oracle-data:
