services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PWD=Oracle_123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./csv:/opt/oracle/csv
    shm_size: 1gb
    mem_limit: 2g
    restart: on-failure

volumes:
  oracle-data:
