DROP TRIGGER DW.TRG_BD2_DIM_HORA_KEY;
DROP TRIGGER DW.TRG_BD2_DIM_SELECCION_KEY;
DROP TRIGGER DW.TRG_BD2_DIM_RONDA_KEY;
DROP TRIGGER DW.TRG_BD2_DIM_PAIS_ORG_KEY;
DROP TRIGGER DW.TRG_BD2_DIM_CIUDAD_KEY;
DROP TRIGGER DW.TRG_BD2_DIM_ESTADIO_KEY;

DROP PROCEDURE DW.PRC_DEVUELVE_CORRELATIVOS;



DROP TRIGGER TRG_TABLA_SINC;
DROP TRIGGER TRG_DIM_HORA;

DROP PROCEDURE PRC_SINCRONIZACION;
DROP PROCEDURE PRC_DIM_HORA;
DROP PROCEDURE PRC_DIM_RONDA;
DROP PROCEDURE PRC_DIM_SELECCION;
DROP PROCEDURE PRC_DIM_ESTADIO;
DROP PROCEDURE PRC_DIM_CIUDAD;
DROP PROCEDURE PRC_DIM_PAIS_ORGANIZADOR;
DROP PROCEDURE PRC_CONSTRUYE_HECHOS;
DROP PROCEDURE PRC_LLENA_SEGUIMIENTO;
DROP PROCEDURE PRC_DIMENSIONES_FALTANTES;
