REVOKE SELECT ON BD2_HECHOS FROM stage;
REVOKE SELECT ON BD2_DIM_HORA FROM stage;
REVOKE SELECT ON BD2_DIM_RONDA FROM stage;
REVOKE SELECT ON BD2_DIM_ESTADIO FROM stage;
REVOKE SELECT ON BD2_DIM_CIUDAD FROM stage;
REVOKE SELECT ON BD2_DIM_PAIS_ORGANIZADOR FROM stage;
REVOKE SELECT ON BD2_DIM_SELECCION FROM stage;

REVOKE INSERT ON BD2_SEGUIMIENTO FROM stage;
REVOKE INSERT ON BD2_SEGUIMIENTO FROM produccion;

ALTER TABLE BD2_DIM_CIUDAD DROP CONSTRAINT FK_CIUDAD_PAIS;
ALTER TABLE BD2_DIM_ESTADIO DROP CONSTRAINT FK_ESTADIO_CIUDAD;


ALTER TABLE BD2_DIM_HORA DROP CONSTRAINT HORA_PK;
ALTER TABLE BD2_DIM_SELECCION DROP CONSTRAINT SELECCION_PK;
ALTER TABLE BD2_DIM_RONDA DROP CONSTRAINT RONDA_PK;
ALTER TABLE BD2_DIM_CIUDAD DROP CONSTRAINT CIUDAD_PK;
ALTER TABLE BD2_DIM_PAIS_ORGANIZADOR DROP CONSTRAINT PAIS_ORGANIZADOR_PK;
ALTER TABLE BD2_DIM_ESTADIO DROP CONSTRAINT ESTADIO_PK;


DROP TABLE BD2_DIM_HORA PURGE;
DROP TABLE BD2_DIM_SELECCION PURGE;
DROP TABLE BD2_DIM_RONDA PURGE;
DROP TABLE BD2_DIM_PAIS_ORGANIZADOR PURGE;
DROP TABLE BD2_DIM_CIUDAD PURGE;
DROP TABLE BD2_DIM_ESTADIO PURGE;
DROP TABLE BD2_HECHOS PURGE;
DROP TABLE BD2_NO_HECHOS PURGE;
DROP TABLE BD2_CORRELATIVOS PURGE;
DROP TABLE BD2_SEGUIMIENTO PURGE;
DROP TABLE BD2_VALORES_DEFAULT PURGE;

